name: code_builder
version: 1.0.0-alpha
description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  analyzer: '>=0.28.1 <0.29.0'
  dart_style: ^0.2.10
  matcher: ^0.12.0+2
  meta: ^1.0.2

dev_dependencies:
  test: ^0.12.0
