name: code_builder
version: 4.0.0

description: >-
  A fluent, builder-based library for generating valid Dart code
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  matcher: ^0.12.10
  meta: ^1.3.0

dev_dependencies:
  build: ^2.0.0
  build_runner: ^1.12.2
  built_value_generator: ^8.0.0
  dart_style: ^2.0.0
  pedantic: ^1.10.0
  source_gen: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  # Due to dependency cycle
  build_runner: ^1.12.2
