name: code_builder
version: 3.1.2

description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  built_collection: '>=1.0.0 <4.0.0'
  built_value: ^5.1.0
  matcher: ^0.12.0
  meta: ^1.0.5

dev_dependencies:
  build: ^0.12.0
  build_runner: '>=0.7.9 <0.9.0'
  built_value_generator: ^5.1.0
  dart_style: ^1.0.0
  source_gen: '>=0.7.5 <0.9.0'
  test: '>=0.12.0 <2.0.0'
