name: code_builder
version: 4.6.0-dev
description: >-
  A fluent, builder-based library for generating valid Dart code
repository: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  matcher: ^0.12.10
  meta: ^1.3.0

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.0.3
  built_value_generator: ^8.0.0
  dart_flutter_team_lints: ^1.0.0
  dart_style: ^2.0.0
  source_gen: ^1.0.0
  test: ^1.16.0
